name: Test

on: 
  workflow_call

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Install test dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --with test

      - name: Testing
        run: poetry run make test