name: Continuous Integration

on: [push]

jobs:

  setup:
    uses: ./.github/workflows/setup.yml

  lint:
    needs: setup
    uses: ./.github/workflows/lint.yml
    #secrets: inherit

  test:
    needs: lint
    uses: ./.github/workflows/test.yml
    #secrets: inherit

