name: Continuous Integration

on: [push]

jobs:

  build:
    name: Build Docker Development Image
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/currency_converter_development
          target: development

  test:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - 
          name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
        - 
          name: Checkout
          uses: actions/checkout@v2
        -
          run: docker pull ${DOCKER_IMAGE}
        -
          name: Testing
          run: docker run --rm -it ${DOCKER_IMAGE} /bin/bash -c "source /app/.venv/bin/activate" -i
          #run: docker run --rm -e -t ${DOCKER_IMAGE} make ivar
      env:
        DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/currency_converter_development
    

  # lint:
  #     needs: build
  #     name: Linting
  #     runs-on: ubuntu-latest
  #     steps:
  #       - 
  #         name: Login to Docker Hub
  #         uses: docker/login-action@v2
  #         with:
  #           username: ${{ secrets.DOCKERHUB_USERNAME }}
  #           password: ${{ secrets.DOCKERHUB_PASSWORD }}
  #       - 
  #         name: Checkout
  #         uses: actions/checkout@v2
  #       -
  #         run: docker pull ${DOCKER_IMAGE}
  #       - 
  #         name: Linting
  #         run: |
  #           docker run --rm -it ${DOCKER_IMAGE} make lint"
  #       -
  #         name: Display lint results
  #         run: cat lint_result.txt
  #     env:
  #       DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/currency_converter_development