name: Continuous Integration

on: [push]

jobs:

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/currency_converter_development:${{github.run_number}}
          target: development

  test:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: ${{ secrets.DOCKERHUB_USERNAME }}/currency_converter_development:${{github.run_number}}
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    steps:
      - 
        run: poetry run make lint
    #secrets: inherit

  # lint:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   image: ${{ secrets.DOCKERHUB_USERNAME }}/currency_converter:${{github.run_number}}
  #   steps:

  

