name: Lint

on: 
  workflow_call

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # - name: Load cached venv
      #   id: cached-poetry-dependencies
      #   uses: actions/cache@v3
      #   with:
      #     path: .venv
      #     key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install lint dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --with lint
      - name: Lint
        run: poetry run make lint