name: Test

on: 
  workflow_call

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - 
        name: Checkout
        uses: actions/checkout@v2
      -
        run: docker pull ${DOCKER_IMAGE}
      - 
        name: Testing
        run: make test
    env:
      DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/currency_converter_development