name: Linting

on: workflow_call

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - 
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Testing
        run: docker run --rm -t ${DOCKER_IMAGE} /bin/bash -c "source /app/.venv/bin/activate && make linting"
    env:
      DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/currency_converter_development